name: presubmit
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
jobs:
  presubmit:
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        go: ["1.22.3"]
    steps:
    - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
    - uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go }}
    - run: go version
    - run: sudo apt-get update && sudo apt-get install -y ripgrep
    - run: ./hack/do_cleanup.sh
    - run: ./hack/do_sync.sh
